stages:   
  - 🔨 build
  - ✅ tests 
  - 🚀 deploy

build:
  stage: 🔨 build
  script:
    - xcodebuild clean -workspace drp14.xcworkspace -scheme drp14 | xcbeautify
    - xcodebuild build -workspace drp14.xcworkspace -scheme drp14 | xcbeautify
    - echo "Build done!"

unit_tests:
  stage: ✅ tests 
  script:
    - bundle exec fastlane unitTests
    - echo "Finish testing unit tests."

UI_tests:
  stage: ✅ tests 
  script:
    - bundle exec fastlane UITests
    - echo "Finish testing UI tests"

deploy-prod:
  stage: 🚀 deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

