build-job:
  stage: build
  script:
    - xcodebuild clean -project frontend/drp14.xcodeproj -scheme drp14 | xcpretty
    - echo "Build done!"

test-job1:
  stage: test
  script:
    - xcodebuild test -project frontend/drp14.xcodeproj -scheme drp14 -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.4' | xcpretty -s
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

