stages:   
  - 🔨 build
  - ✅ tests 
  - 🚀 deploy

build:
  stage: 🔨 build
  script:
    - xcodebuild clean -workspace drp14.xcworkspace -scheme drp14 | xcbeautify
    - xcodebuild build -workspace drp14.xcworkspace -scheme drp14 | xcbeautify
    - echo "Build done!"

frontend_tests:
  stage: ✅ tests 
  script:
    - bundle exec fastlane tests
    - echo "Finish testing unit tests and UI tests of the iOS part"

backend_tests:
  stage: ✅ tests 
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: 🚀 deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

