# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#### device iPhone 12 Pro (and probably similar devices) are not supported!

default_platform(:ios)

platform :ios do
  desc "run unit tests"
  lane :unitTests do
    run_tests(
      scheme: "drp14",
      skip_build: true,
      only_testing: ["drp14Tests"]
    )
  end

  desc "run UI tests"
  lane :UITests do
    run_tests(
      scheme: "drp14",
      skip_build: true,
      only_testing: ["drp14UITests"]
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
