spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/php?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#    username: root
#    password: Qxz010424. #数据库名、用户名和密码改为自己的
#    driver-class-name: com.mysql.cj.jdbc.Driver
